name: Docker Build and Push

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract tag and repo owner in lowercase
      id: meta
      run: |
        TAG_NAME=$(echo "${GITHUB_REF##*/}")
        OWNER_LOWER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
        echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "owner=$OWNER_LOWER" >> $GITHUB_OUTPUT

    - name: Build and push to Docker Hub and GHCR
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          deepakdocker25/resizeimage:${{ steps.meta.outputs.tag }}
          ghcr.io/${{ steps.meta.outputs.owner }}/resizeimage:${{ steps.meta.outputs.tag }}
